extraction:
  cpp:
    prepare:
      packages:
        - bison
        - cmake
        - flex
        - g++
        - git
        - libelf-dev
        - libgtest-dev
        - libgmock-dev
        - zlib1g-dev
        - libfl-dev
        - systemtap-sdt-dev
        - binutils-dev
        - llvm-7-dev
        - llvm-7-runtime
        - libclang-7-dev
        - clang-7
        - libbpfcc-dev
    after_prepare:
      - cd $LGTM_WORKSPACE
      - mkdir -p local/lib
      - git clone https://github.com/libbpf/libbpf.git
      - cd libbpf/src
      - git checkout v0.8.0
      - CC=gcc make -j$(nproc)
      - PREFIX=$LGTM_WORKSPACE/local LIBDIR=$LGTM_WORKSPACE/local/lib make install install_uapi_headers
      - export CPATH=$LGTM_WORKSPACE/local/include:$CPATH
      - export LD_LIBRARY_PATH=$LGTM_WORKSPACE/local/lib:$LD_LIBRARY_PATH

