extraction:
  cpp:
    prepare:
      packages:
        - bison
        - cmake
        - flex
        - g++
        - git
        - libelf-dev
        - zlib1g-dev
        - libfl-dev
        - systemtap-sdt-dev
        - binutils-dev
        - llvm-7-dev
        - llvm-7-runtime
        - libclang-7-dev
        - clang-7
        - libbpfcc-dev
