FROM fedora:27
RUN dnf install -y \
    bison \
    clang-devel \
    cmake \
    elfutils-libelf-devel \
    flex \
    gcc-c++ \
    git \
    llvm-devel \
    make \
    zlib-devel

COPY build.sh /build.sh
ENTRYPOINT ["/bin/sh", "/build.sh"]
