FROM fedora:30
RUN dnf install -y \
    bison \
    binutils-devel \
    cereal-devel \
    clang-devel \
    cmake \
    elfutils-libelf-devel \
    flex \
    gcc-c++ \
    git \
    gtest-devel \
    gmock-devel \
    llvm-devel \
    make \
    zlib-devel \
    bcc-devel \
    systemtap-sdt-devel

COPY build.sh /build.sh
RUN chmod 755 /build.sh
ENTRYPOINT ["/bin/sh", "/build.sh"]
