FROM alpine:3.11

RUN apk add --update \
  bash \
  bison \
  bcc-dev \
  bcc-static \
  libbpf-dev \
  build-base \
  clang-dev \
  clang-static \
  cmake \
  elfutils-dev \
  flex-dev \
  git \
  linux-headers \
  llvm9-dev \
  llvm9-static \
  python3 \
  zlib-dev \
  zlib-static

WORKDIR /

RUN mv /usr/lib/libbccbpf.a /usr/lib/libbcc_bpf.a

COPY build.sh /build.sh
RUN chmod 755 /build.sh
ENTRYPOINT ["/bin/sh", "/build.sh"]
