.TH cpuwalk 8  "2018-09-08" "USER COMMANDS"
.SH NAME
cpuwalk.bt \- Sample which CPUs are executing processes.. Uses bpftrace/eBPF.
.SH SYNOPSIS
.B cpuwalk.bt
.SH DESCRIPTION
This tool samples CPUs at 99 Hertz, then prints a histogram showing which
CPUs were active. 99 Hertz is used to avoid lockstep sampling that would
skew results. This tool can help identify if your application's workload is
evenly using the CPUs, or if there is an imbalance problem.

Since this uses BPF, only the root user can use this tool.
.SH REQUIREMENTS
CONFIG_BPF and bpftrace.
.SH EXAMPLES
.TP
Sample CPUs and print a summary on Ctrl-C:
#
.B cpuwalk.bt
.SH FIELDS
.TP
1st, 2nd
The CPU is shown in the first field, after the "[". Disregard the second field.
.TP
3rd
A column showing the number of samples for this CPU.
.TP
4th
This is an ASCII histogram representing the count column.
.SH OVERHEAD
This should be negligible.
.SH SOURCE
This is from bpftrace.
.IP
https://github.com/iovisor/bpftrace
.PP
Also look in the bpftrace distribution for a companion _examples.txt file containing
example usage, output, and commentary for this tool.
.SH OS
Linux
.SH STABILITY
Unstable - in development.
.SH AUTHOR
Brendan Gregg
.SH SEE ALSO
mpstat(1)
