= bpftrace(8)
:doctype: manpage
:toc: true
:toclevels: 1

////
Style guide:
- one sentence per line
////

== Name

bpftrace - a high-level tracing language

== Synopsis

*bpftrace* [_OPTIONS_] _FILENAME_ +
*bpftrace* [_OPTIONS_] -e 'program code'

When _FILENAME_ is "_-_", bpftrace will read program code from stdin.

A program will continue running until Ctrl-C is hit, or an `exit` function is called.
When a program exits, all populated maps are printed (more details below).

== Description

bpftrace is a high-level tracing language for Linux. bpftrace uses LLVM as
a backend to compile scripts to eBPF-bytecode and makes use of libbpf and bcc
for interacting with the Linux BPF subsystem, as well as existing Linux
tracing capabilities.

== Examples

Trace processes calling sleep::
----
# bpftrace -e 'kprobe:do_nanosleep { printf("%d sleeping\n", pid); }'
----

Trace processes calling sleep while spawning `sleep 5` as a child process::
----
# bpftrace -e 'kprobe:do_nanosleep { printf("%d sleeping\n", pid); }' -c 'sleep 5'
----

List all probes with "sleep" in their name::
----
# bpftrace -l '*sleep*'
----

List all the probes attached in the program::
----
# bpftrace -l -e 'kprobe:do_nanosleep { printf("%d sleeping\n", pid); }'
----

== Options

=== *-B* _MODE_

Set the buffer mode for stdout.

Valid values are::
*none* No buffering. Each I/O is written as soon as possible +
*line* Data is written on the first newline or when the buffer is full. This is the default mode. +
*full* Data is written once the buffer is full.

=== *-c* _COMMAND_

Run _COMMAND_ as a child process.
When the child terminates bpftrace will also terminate, as if 'exit()' had been called.
If bpftrace terminates before the child process does the child process will be terminated with a SIGTERM.
If used, 'USDT' probes will only be attached to the child process.
To avoid a race condition when using 'USDTs', the child is stopped after 'execve' using 'ptrace(2)' and continued when all 'USDT' probes are attached.
The child process runs with the same privileges as bpftrace itself (usually root).

Unless otherwise specified, bpftrace does not perform any implicit filtering. Therefore, if you are only interested in
events in _COMMAND_, you may want to filter based on the child PID. The child PID is available to programs as the 'cpid' builtin.
For example, you could add the predicate `/pid == cpid/` to probes with userspace context.

=== *-d STAGE*

Enable debug mode.
For more details see the <<Debug Output>> section.

=== *--dry-run*

Terminate execution right after attaching all the probes. Useful for testing
that the script can be parsed, loaded, and attached, without actually running
it.

=== *-e* _PROGRAM_

Execute _PROGRAM_ instead of reading the program from a file or stdin.

=== *-f* _FORMAT_

Set the output format.

Valid values are::
*json* +
*text*

The JSON output is compatible with NDJSON and JSON Lines, meaning each line of the streamed output is a single blob of valid JSON.

=== *-h, --help*

Print the help summary.

=== *-I* _DIR_

Add the directory _DIR_ to the search path for C headers.
This option can be used multiple times.
For more details see the <<Preprocessor Options>> section.

=== *--include* _FILENAME_

Add _FILENAME_ as an include for the pre-processor.
This is equal to adding '#include _FILENAME_' at the top of the program.
This option can be used multiple times.
For more details see the <<Preprocessor Options>> section.

=== *--info*

Print detailed information about features supported by the kernel and the bpftrace build.

=== *-k*

This flag enables runtime warnings for errors from 'probe_read_*' and map lookup BPF helpers.
When errors occur bpftrace will log an error containing the source location and the error code:

----
stdin:48-57: WARNING: Failed to probe_read_user_str: Bad address (-14)
u:lib.so:"fn(char const*)" { printf("arg0:%s\n", str(arg0));}
                                                 ~~~~~~~~~
----

=== *-l* [_SEARCH_|_FILENAME_]

List all probes that match the _SEARCH_ pattern.
If the pattern is omitted all probes will be listed.
This pattern supports wildcards in the same way that probes do.
E.g. '-l kprobe:*file*' to list all 'kprobes' with 'file' in the name.
This can be used with a program, which will list all probes in that program.
For more details see the <<Listing Probes>> section.

=== *--no-feature* _feature,feature,..._

Disable use of detected features, valid values are::
*uprobe_multi* to disable uprobe_multi link +
*kprobe_multi* to disable kprobe_multi link +
*kprobe_session* to disable automatic collapse of kprobe/kretprobe into kprobe session

=== *--no-warnings*

Suppress all warning messages created by bpftrace.

=== *-o* _FILENAME_

Write bpftrace tracing output to _FILENAME_ instead of stdout.
This doesn't include child process (*-c* option) output.
Errors are still written to stderr.

=== *-p* _PID_

Attach to the process with or filter actions by _PID_.
If the process terminates, bpftrace will also terminate.
When using USDT, uprobes, uretprobes, hardware, software, profile, interval, watchpoint, or asyncwatchpoint probes they will be attached to only this process.
For all other probes, except BEGIN/END, the pid will act like a predicate to filter out events not from that pid.
For listing uprobes/uretprobes set the target to '*' and the process's address space will be searched for the symbols.

=== *-q*

Keep messages quiet.

=== *--unsafe*

Some calls, like 'system', are marked as unsafe as they can have dangerous side effects ('system("rm -rf")') and are disabled by default.
This flag allows their use.

=== *--usdt-file-activation*

Activate usdt semaphores based on file path.

=== *-V, --version*

Print bpftrace version information.

=== *-v*

Enable verbose messages.
For more details see the <<Verbose Output>> section.

=== Program Options

You can also pass custom options to a bpftrace program/script itself via positional or named parameters.
Positional parameters can be placed before or after a double dash but named parameters can ONLY come after a double dash; e.g.
```
# bpftrace -e 'BEGIN { print(($1, $2, getopt("aa", 1), getopt("bb"))); }' p1 -- --aa=20 --bb p2

// (p1, p2, 20, true) is printed
```
or
```
# bpftrace myscript.bt -- p1 --aa=20 --bb p2
```

In these examples there are two positional parameters (`p1`, `p2`) and two named parameters (`aa`, which is set to `20`, and `bb`, which is set to `true`).
Named program parameters require the `=` to set their value unless they are boolean parameters (like 'bb' above).
Read about how to access <<builtins-positional-parameters, positional>> or <<functions-getopt, named>> parameters in a bpftrace script below.

== The Language

The `bpftrace` (`bt`) language is inspired by the D language used by `dtrace` and uses the same program structure.
Each script consists of a <<Preamble>>, an optional <<Config Block>>, and one or more <<Action Block>>s.

----
preamble

config

actionblock1
actionblock2
----

=== Action Block

Each action block consists of three parts:

----
probe[,probe]
/predicate/ {
  action
}
----

Probes::
  A probe specifies the event and event type to attach to. <<Probes, Probes list>>.

Predicate::
  The predicate is an optional condition that must be met for the action to be executed.

Action::
  Actions are the programs that run when an event fires (and the predicate is met).
An action is a semicolon (`;`) separated list of statements and always enclosed by brackets `{}`.

A basic script that traces the `open(2)` and `openat(2)` system calls can be written as follows:

----
BEGIN {
	printf("Tracing open syscalls... Hit Ctrl-C to end.\n");
}

tracepoint:syscalls:sys_enter_open,
tracepoint:syscalls:sys_enter_openat {
	printf("%-6d %-16s %s\n", pid, comm, str(args.filename));
}
----

The above script has two action blocks and a total of 3 probes.

The first action block uses the special `BEGIN` probe, which fires once during `bpftrace` startup.
This probe is used to print a header, indicating that the tracing has started.

The second action block uses two probes, one for `open` and one for `openat`, and defines an action that prints the file being `open` ed as well as the `pid` and `comm` of the process that execute the syscall.
See the <<Probes>> section for details on the available probe types.

=== Arrays

bpftrace supports accessing one-dimensional arrays like those found in `C`.

Constructing arrays from scratch, like `int a[] = {1,2,3}` in `C`, is not supported.
They can only be read into a variable from a pointer.

The `[]` operator is used to access elements.

----
struct MyStruct {
  int y[4];
}

kprobe:dummy {
  $s = (struct MyStruct *) arg0;
  print($s->y[0]);
}
----

=== Comments

Both single line and multi line comments are supported.

----
// A single line comment
interval:s:1 { // can also be used to comment inline
/*
 a multi line comment

*/
  print(/* inline comment block */ 1);
}
----

=== Conditionals

Conditional expressions are supported in the form of if/else statements and the ternary operator.

The ternary operator consists of three operands: a condition followed by a `?`, the expression to execute when the condition is true followed by a `:` and the expression to execute if the condition is false.

----
condition ? ifTrue : ifFalse
----

Both the `ifTrue` and `ifFalse` expressions must be of the same type, mixing types is not allowed.

The ternary operator can be used as part of an assignment.

----
$a == 1 ? print("true") : print("false");
$b = $a > 0 ? $a : -1;
----

If/else statements, like the one in `C`, are supported.

----
if (condition) {
  ifblock
} else if (condition) {
  if2block
} else {
  elseblock
}
----

=== Config Block

To improve script portability, you can set bpftrace <<Config Variables>> via the config block,
which can only be placed at the top of the script before any action blocks (even `BEGIN`).

----
config = {
    stack_mode=perf;
    max_map_keys=2
}

BEGIN { ... }

uprobe:./testprogs/uprobe_test:uprobeFunction1 { ... }
----

The names of the config variables can be in the format of environment variables
or their lowercase equivalent without the `BPFTRACE_` prefix. For example,
`BPFTRACE_STACK_MODE`, `STACK_MODE`, and `stack_mode` are equivalent.

**Note**: Environment variables for the same config take precedence over those set
inside a script config block.

<<Config Variables, List of All Config Variables>>

=== Data Types

The following fundamental types are provided by the language.
Note: Integers are by default represented as 64 bit signed but that can be
changed by either casting them or, for scratch variables, explicitly specifying
the type upon declaration.

[cols="~,~"]
|===
|*Type*
|*Description*

|bool
|`true` or `false`

|uint8
|Unsigned 8 bit integer

|int8
|Signed 8 bit integer

|uint16
|Unsigned 16 bit integer

|int16
|Signed 16 bit integer

|uint32
|Unsigned 32 bit integer

|int32
|Signed 32 bit integer

|uint64
|Unsigned 64 bit integer

|int64
|Signed 64 bit integer
|===

----
BEGIN { $x = 1<<16; printf("%d %d\n", (uint16)$x, $x); }

/*
 * Output:
 * 0 65536
 */
----

=== Filters/Predicates

Filters (also known as predicates) can be added after probe names.
The probe still fires, but it will skip the action unless the filter is true.

----
kprobe:vfs_read /arg2 < 16/ {
  printf("small read: %d byte buffer\n", arg2);
}

kprobe:vfs_read /comm == "bash"/ {
  printf("read by %s\n", comm);
}
----

=== Floating-point

Floating-point numbers are not supported by BPF and therefore not by bpftrace.

=== Identifiers

Identifiers must match the following regular expression: `[_a-zA-Z][_a-zA-Z0-9]*`

=== Literals

Integer and string literals are supported.

Integer literals can be defined in the following formats:

- decimal (base 10)
- octal (base 8)
- hexadecimal (base 16)
- scientific (base 10)

Octal literals have to be prefixed with a `0` e.g. `0123`.
Hexadecimal literals start with either `0x` or `0X` e.g. `0x10`.
Scientific literals are written in the `<m>e<n>` format which is a shorthand for `m*10^n` e.g. `$i = 2e3;`.
Note that scientific literals are integer only due to the lack of floating point support e.g. `1e-3` is not valid.

To improve the readability of big literals an underscore `_` can be used as field separator e.g. 1_000_123_000.

Integer suffixes as found in the C language are parsed by bpftrace to ensure compatibility with C headers/definitions but they're not used as size specifiers.
`123UL`, `123U` and `123LL` all result in the same integer type with a value of `123`.

These duration suffixes are also supported: `ns`, `us`, `ms`, `s`, `m`, `h`, and `d`. All get turned into integer values in nanoseconds, e.g.
```
$a = 1m;
print($a); // prints 60000000000
```

Character literals are not supported at this time, and the corresponding ASCII code must be used instead:

----
BEGIN {
  printf("Echo A: %c\n", 65);
}
----

String literals can be defined by enclosing the character string in double quotes e.g. `$str = "Hello world";`.

Strings support the following escape sequences:

[cols="~,~"]
|===
| \n
|Newline

| \t
|Tab

| \0nn
|Octal value nn

| \xnn
|Hexadecimal value nn

|===

=== Loops

==== For

With Linux 5.13 and later, `for` loops can be used to iterate over elements in a map, or over a range of integers, provided as two unary expressions separated by `..`.

----
for ($kv : @map) {
  block;
}
----

----
for ($i : start..end) {
  block;
}
----

The variable declared in the `for` loop will be initialised on each iteration.

If the iteration is over a map, the value will be a tuple containing a key and a value from the map, i.e. `$kv = (key, value)`:

----
@map[10] = 20;
for ($kv : @map) {
  print($kv.0); // key
  print($kv.1); // value
}
----

If a map has multiple keys, the loop variable will be initialised with nested tuple of the form: `((key1, key2, ...), value)`:

----
@map[10,11] = 20;
for ($kv : @map) {
  print($kv.0.0); // key 1
  print($kv.0.1); // key 2
  print($kv.1);   // value
}
----

If an integer range is provided, the value will be an integer value for each element in the range, inclusive of the start value and exclusive of the end value:

----
for ($cpu : 0..ncpus) {
  print($cpu); // current value in range
}
----

Note that you cannot adjust the range itself after the loop has started.
The `for` start and end values are evaluated once, not on each loop iteration.
For example, the following will print `0` through `9`:

----
$a = 10;
for ($i : 0..$a) {
  print($i);
  $a--;
}
----

Both `for` loops support the following control flow statements:

[cols="~,~"]
|===

| continue
| skip processing of the rest of the block and proceed to the next iteration

| break
| terminate the loop

|===

==== While

Since kernel 5.3 BPF supports `while` loops as long as the verifier can prove they're bounded and fit within the instruction limit.

----
while (condition) {
  block;
}
----

----
interval:s:1 {
  $i = 0;
  while ($i <= 100) {
    printf("%d ", $i);
    if ($i > 5) {
      break;
    }
    $i++
  }
  printf("\n");
}
----

The `while` loop supports the following control flow statements:

[cols="~,~"]
|===

| continue
| skip processing of the rest of the block and return to the conditional

| break
| terminate the loop

|===

==== Unroll

Loop unrolling is also supported with the `unroll` statement.

----
unroll(n) {
  block;
}
----

The compiler will evaluate the block `n` times and generate the BPF code for the block `n` times.
As this happens at compile time `n` must be a constant greater than 0 (`n > 0`).

The following two probes compile into the same code:

----
interval:s:1 {
  unroll(3) {
    print("Unrolled")
  }
}

interval:s:1 {
  print("Unrolled")
  print("Unrolled")
  print("Unrolled")
}
----

=== Operators and Expressions

==== Arithmetic Operators

The following operators are available for integer arithmetic:

[cols="~,~"]
|===
| +
|integer addition

| -
|integer subtraction

| *
|integer multiplication

| /
|integer division

| %
|integer modulo

|===

Operations between a signed and an unsigned integer are allowed providing
bpftrace can statically prove a safe conversion is possible. If safe conversion
is not guaranteed, the operation is undefined behavior and a corresponding
warning will be emitted.

If the two operands are different size, the smaller integer is implicitly
promoted to the size of the larger one. Sign is preserved in the promotion.
For example, `(uint32)5 + (uint8)3` is converted to `(uint32)5 + (uint32)3`
which results in `(uint32)8`.

Pointers may be used with arithmetic operators but only for addition and
subtraction. For subtraction, the pointer must appear on the left side of the
operator. Pointers may also be used with logical operators; they are considered
true when non-null.

==== Logical Operators

[cols="~,~"]
|===
| &&
| Logical AND

| \|\|
| Logical OR

| !
| Logical NOT

|===

==== Bitwise Operators

[cols="~,~"]
|===
| &
| AND

| \|
| OR

| ^
| XOR

| <<
| Left shift the left-hand operand by the number of bits specified by the right-hand expression value

| >>
| Right shift the left-hand operand by the number of bits specified by the right-hand expression value
|===

==== Relational Operators

The following relational operators are defined for integers and pointers.

[cols="~,~"]
|===
| <
| left-hand expression is less than right-hand

| \<=
| left-hand expression is less than or equal to right-hand

| >
| left-hand expression is bigger than right-hand

| >=
| left-hand expression is bigger or equal to than right-hand

| ==
| left-hand expression equal to right-hand

| !=
| left-hand expression not equal to right-hand

|===

The following relation operators are available for comparing strings and integer arrays.

[cols="~,~"]
|===

| ==
| left-hand string equal to right-hand

| !=
| left-hand string not equal to right-hand

|===

==== Assignment Operators

The following assignment operators can be used on both `map` and `scratch` variables:

[cols="~,~"]
|===

| =
| Assignment, assign the right-hand expression to the left-hand variable

| <\<=
| Update the variable with its value left shifted by the number of bits specified by the right-hand expression value

| >>=
| Update the variable with its value right shifted by the number of bits specified by the right-hand expression value

| +=
| Increment the variable by the right-hand expression value

| -=
| Decrement the variable by the right-hand expression value

| *=
| Multiple the variable by the right-hand expression value

| /=
| Divide the variable by the right-hand expression value

| %=
| Modulo the variable by the right-hand expression value

| &=
| Bitwise AND the variable by the right-hand expression value

| \|=
| Bitwise OR the variable by the right-hand expression value

| ^=
| Bitwise XOR the variable by the right-hand expression value

|===

All these operators are syntactic sugar for combining assignment with the specified operator.
`@ -= 5` is equal to `@ = @ - 5`.

==== Increment and Decrement Operators

The increment (`{plus}{plus}`) and decrement (`--`) operators can be used on integer and pointer variables to increment their value by one.
They can only be used on variables and can either be applied as prefix or suffix.
The difference is that the expression `x{plus}{plus}` returns the original value of `x`, before it got incremented while `{plus}{plus}x` returns the value of `x` post increment.

----
$x = 10;
$y = $x--; // y = 10; x = 9
$a = 10;
$b = --$a; // a = 9; b = 9
----

Note that maps will be implicitly declared and initialized to 0 if not already declared or defined.
Scratch variables must be initialized before using these operators.

Note `{plus}{plus}`/`--` on a shared global variable can lose updates. See <<map-functions-count, `count()`>> for more details.

==== Block Expressions

A block can be used as expression, as long as the last statement of the block
is an expression with no trailing semi-colon.

```
let $a = {
  let $b = 1;
  $b
};
// $a is 1
```

This can be used anywhere an expression can be used.

=== Preamble

Preprocessor and type definitions take place in the preamble:

----
#include <linux/socket.h>
#define RED "\033[31m"

struct S {
  int x;
}
----

=== Pointers

Pointers in bpftrace are similar to those found in `C`.
// TODO, not true yet

=== Structs

`C` like structs are supported by bpftrace.
Fields are accessed with the `.` operator.
Fields of a pointer to a struct can be accessed with the `\->` operator.

Custom structs can be defined in the preamble.

Constructing structs from scratch, like `struct X var = {.f1 = 1}` in `C`, is not supported.
They can only be read into a variable from a pointer.

----
struct MyStruct {
  int a;
}

kprobe:dummy {
  $ptr = (struct MyStruct *) arg0;
  $st = *$ptr;
  print($st.a);
  print($ptr->a);
}
----

=== Tuples

bpftrace has support for immutable N-tuples (`n > 1`).
A tuple is a sequence type (like an array) where, unlike an array, every element can have a different type.

Tuples are a comma separated list of expressions, enclosed in brackets, `(1,2)`
Individual fields can be accessed with the `.` operator.
Tuples are zero indexed like arrays are.

----
interval:s:1 {
  $a = (1,2);
  $b = (3,4, $a);
  print($a);
  print($b);
  print($b.0);
}

/*
 * Sample output:
 * (1, 2)
 * (3, 4, (1, 2))
 * 3
 */
----

=== Type conversion

Integer and pointer types can be converted using explicit type conversion with an expression like:

----
$y = (uint32) $z;
$py = (int16 *) $pz;
----

Integer casts to a higher rank are sign extended.
Conversion to a lower rank is done by zeroing leading bits.

It is also possible to cast between integers and integer arrays using the same syntax:

----
$a = (uint8[8]) 12345;
$x = (uint64) $a;
----

Both the cast and the destination type must have the same size.
When casting to an array, it is possible to omit the size which will be determined automatically from the size of the cast value.

Integers are internally represented as 64 bit signed. If you need another representation, you may cast to the supported <<Data Types>>.

==== Array casts

It is possible to cast between integer arrays and integers.
Both the source and the destination type must have the same size.
The main purpose of this is to allow casts from/to byte arrays.

----
BEGIN {
  $a = (int8[8])12345;
  printf("%x %x\n", $a[0], $a[1]);
  printf("%d\n", (uint64)$a);
}

/*
 * Output:
 * 39 30
 * 12345
 */
----

When casting to an array, it is possible to omit the size which will be determined automatically from the size of the cast value.

This feature is especially useful when working with IP addresses since various libraries, builtins, and parts of the kernel use different approaches to represent addresses (usually byte arrays vs. integers).
Array casting allows seamless comparison of such representations:

----
fentry:tcp_connect {
    if (args->sk->__sk_common.skc_daddr == (uint32)pton("127.0.0.1"))
        ...
}
----

=== Variables and Maps

bpftrace knows two types of variables, 'scratch' and 'map'.

'scratch' variables are kept on the BPF stack and their names always start
with a `$`, e.g. `$myvar`.
'scratch' variables cannot be accessed outside of their lexical block e.g.
```
$a = 1;
if ($a == 1) {
  $b = "hello"
  $a = 2;
}
// $b is not accessible here
```

'scratch' variables can also declared before or during initialization with `let` e.g.
```
let $a = 1;
let $b;
if ($a == 1) {
  $b = "hello"
  $a = 2;
}
// $b IS accessible here and would be an empty string if the condition wasn't true
```

If no assignment is specified variables will initialize to 0.

'map' variables use BPF 'maps'.
These exist for the lifetime of `bpftrace` itself and can be accessed from all action blocks and user-space.
Map names always start with a `@`, e.g. `@mymap`.

All valid identifiers can be used as `name`.

The data type of a variable is automatically determined during first assignment and cannot be changed afterwards.

==== Map Declarations

**Warning** this feature is experimental and may be subject to changes.
Stabilization is tracked in link:https://github.com/bpftrace/bpftrace/issues/4077[#4077].

Maps can also be declared in the global scope, before probes and after the config e.g.
----
let @a = hash(100);
let @b = percpulruhash(20);

BEGIN { ... }
----

The utility of this is that you can specify different underlying BPF map types.
Currently these are available in bpftrace:
- hash (BPF_MAP_TYPE_HASH)
- lruhash (BPF_MAP_TYPE_LRU_HASH)
- percpuhash (BPF_MAP_TYPE_PERCPU_HASH)
- percpulruhash (BPF_MAP_TYPE_LRU_PERCPU_HASH)
- percpuarray (BPF_MAP_TYPE_PERCPU_ARRAY)

Additionally, map declarations must supply a single argument: **max entries** e.g. `let @a = lruhash(100);`
All maps that are not declared in the global scope utilize the default set in the config variable "max_map_keys".
However, it's best practice to declare maps up front as using the default can lead to lost map update events (if the map is full) or over allocation of memory if the map is intended to only store a few entries.

**Warning** The "lru" variants of hash and percpuhash evict the approximately least recently used elements. In other words, users should not rely on the accuracy on the part of the eviction algorithm. Adding a single new element may cause one or multiple elements to be deleted if the map is at capacity. link:https://docs.ebpf.io/linux/map-type/BPF_MAP_TYPE_LRU_HASH/[Read more about LRU internals].

==== Maps without Explicit Keys

Values can be assigned directly to maps without a key (sometimes refered to as scalar maps).
Note: you can't iterate over these maps as they don't have an accessible key.

----
@name = expression
----

==== Map Keys

Setting single value map keys.

----
@name[key] = expression
----

Map keys that are composed of multiple values are represented as tuples e.g.

----
@name[(key1,key2)] = expression
----

However, this, more concise, syntax is supported and the same as the explicit
tuple above:

----
@name[key1,key2] = expression
----

Just like with any variable the type is determined on first use and cannot be modified afterwards.
This applies to both the key(s) and the value type.

The following snippets create a map with key signature `(int64, string)` and a value type of `int64`:

----
@[pid, comm]++
@[(pid, comm)]++
----

==== Macros

**Warning** this feature is experimental and may be subject to changes.
Stabilization is tracked in link:https://github.com/bpftrace/bpftrace/issues/4079[#4079].

bpftrace macros (as opposed to C macros) provide a way for you to structure your script.
They can be useful when you want to factor out code into smaller, more understandable parts.
Or if you want to share code between probes.

At a high level, macros can be thought of as semantic aware text replacement.
They accept (optional) variable, map, and some expression arguments.
The body of the macro may only access maps and external variables passed in through the arguments, which is why these are often referred to as "hygienic macros".

For example, these are valid usages of macros:

----
macro one() {
  1
}

macro plus_one($other_name) {
  $other_name + 1
}

macro add_one_to_each($a, @b) {
  $a += 1;
  @b += 1;
}

macro side_effect($x) {
  print($x)
}

macro add_two($x) {
  add_one($x) + 1
}

BEGIN {
  print(one());                   // prints 1

  $a = 10;
  print(plus_one($a));            // prints 11

  @b = 5;
  add_one_to_each($a, @b);
  print($a + @b)                  // prints 17

  side_effect(5)                  // prints 5

  print(add_two(1));              // prints 3
}
----

Some examples of invalid macro usage:

----
macro unhygienic_access() {
  @x++                         // BAD: @x not passed in
}

macro wrong_parameter_type($x) {
  $x++
}

BEGIN {
  @x = 1;
  unhygienic_access();

  wrong_parameter_type(@x);    // BAD: macro expects a scratch variable
}
----

==== Per-Thread Variables

These can be implemented as a map keyed on the thread ID. For example, `@start[tid]`:

----
kprobe:do_nanosleep {
  @start[tid] = nsecs;
}

kretprobe:do_nanosleep /has_key(@start, tid)/ {
  printf("slept for %d ms\n", (nsecs - @start[tid]) / 1000000);
  delete(@start, tid);
}

/*
 * Sample output:
 * slept for 1000 ms
 * slept for 1009 ms
 * slept for 2002 ms
 * ...
 */
----

This style of map may also be useful for capturing output parameters, or other context, between two different probes. For example:

----
tracepoint:syscalls:sys_enter_wait4
{
  @out[tid] = args.ru;
}

tracepoint:syscalls:sys_exit_wait4
{
  $ru = @out[tid];
  delete(@out, tid);
  if ($ru != 0) {
    printf("got usage ...", ...);
  }
}
----

== Probes

bpftrace supports various probe types which allow the user to attach BPF programs to different types of events.
Each probe starts with a provider (e.g. `kprobe`) followed by a colon (`:`) separated list of options.
The amount of options and their meaning depend on the provider and are detailed below.
The valid values for options can depend on the system or binary being traced, e.g. for uprobes it depends on the binary.
Also see <<Listing Probes>>.

It is possible to associate multiple probes with a single action as long as the action is valid for all specified probes.
Multiple probes can be specified as a comma (`,`) separated list:

----
kprobe:tcp_reset,kprobe:tcp_v4_rcv {
  printf("Entered: %s\n", probe);
}
----

Wildcards are supported too:

----
kprobe:tcp_* {
  printf("Entered: %s\n", probe);
}
----

Both can be combined:

----
kprobe:tcp_reset,kprobe:*socket* {
  printf("Entered: %s\n", probe);
}
----

By default, bpftrace requires all probes to attach successfully or else an error is returned. However this can be changed using the `missing_probes` config variable.

Most providers also support a short name which can be used instead of the full name, e.g. `kprobe:f` and `k:f` are identical.

[cols="~,~,~"]
|===
|*Probe Name*
|*Short Name*
|*Description*

| <<probes-begin-end, `BEGIN/END`>>
| -
| Built-in events

| <<probes-self, `self`>>
| -
| Built-in events

| <<probes-hardware, `hardware`>>
| `h`
| Processor-level events

| <<probes-interval, `interval`>>
| `i`
| Timed output

| <<probes-iterator, `iter`>>
| `it`
| Iterators tracing

| <<probes-fentry, `fentry/fexit`>>
| `f`/`fr`
| Kernel functions tracing with BTF support

| <<probes-kprobe, `kprobe/kretprobe`>>
| `k`/`kr`
| Kernel function start/return

| <<probes-profile, `profile`>>
| `p`
| Timed sampling

| <<probes-rawtracepoint, `rawtracepoint`>>
| `rt`
| Kernel static tracepoints with raw arguments

| <<probes-software, `software`>>
| `s`
| Kernel software events

| <<probes-tracepoint, `tracepoint`>>
| `t`
| Kernel static tracepoints

| <<probes-uprobe, `uprobe/uretprobe`>>
| `u`/`ur`
| User-level function start/return

| <<probes-usdt, `usdt`>>
| `U`
| User-level static tracepoints

| <<probes-watchpoint, `watchpoint/asyncwatchpoint`>>
| `w`/`aw`
| Memory watchpoints
|===

[#probes-begin-end]
=== BEGIN/END

These are special built-in events provided by the bpftrace runtime.
`BEGIN` is triggered before all other probes are attached.
`END` is triggered after all other probes are detached.

Note that specifying an `END` probe doesn't override the printing of 'non-empty' maps at exit.
To prevent printing all used maps need be cleared in the `END` probe:

----
END {
    clear(@map1);
    clear(@map2);
}
----

[#probes-self]
=== self

.variants
* `self:signal:SIGUSR1`

These are special built-in events provided by the bpftrace runtime.
The trigger function is called by the bpftrace runtime when the bpftrace process receives specific events, such as a `SIGUSR1` signal.

----
self:signal:SIGUSR1 {
  print("abc");
}
----

[#probes-hardware]
=== hardware

.variants
* `hardware:event_name:`
* `hardware:event_name:count`

.short name
* `h`

These are the pre-defined hardware events provided by the Linux kernel, as commonly traced by the perf utility.
They are implemented using performance monitoring counters (PMCs): hardware resources on the processor.
There are about ten of these, and they are documented in the perf_event_open(2) man page.
The event names are:

- `cpu-cycles` or `cycles`
- `instructions`
- `cache-references`
- `cache-misses`
- `branch-instructions` or `branches`
- `branch-misses`
- `bus-cycles`
- `frontend-stalls`
- `backend-stalls`
- `ref-cycles`

The `count` option specifies how many events must happen before the probe fires (sampling interval).
If `count` is left unspecified a default value is used.

This will fire once for every 1,000,000 cache misses.

----
hardware:cache-misses:1e6 { @[pid] = count(); }
----

[#probes-interval]
=== interval

.variants
* `interval:count`
* `interval:us:count`
* `interval:ms:count`
* `interval:s:count`
* `interval:hz:rate`

.short name
* `i`

The interval probe fires at a fixed interval as specified by its time spec.
Interval fires on one CPU at a time, unlike <<probes-profile>> probes.
If a unit of time is not specified in the second position, the number is interpreted as nanoseconds; e.g., `interval:1s`, `interval:1000000000`, and `interval:s:1` are all equivalent.

This prints the rate of syscalls per second.

----
tracepoint:raw_syscalls:sys_enter { @syscalls = count(); }
interval:1s { print(@syscalls); clear(@syscalls); }
----

[#probes-iterator]
=== iterator

.variants
* `iter:task`
* `iter:task:pin`
* `iter:task_file`
* `iter:task_file:pin`
* `iter:task_vma`
* `iter:task_vma:pin`

.short name
* `it`

**Warning** this feature is experimental and may be subject to interface changes.

These are eBPF iterator probes that allow iteration over kernel objects.
Iterator probe can't be mixed with any other probe, not even another iterator.
Each iterator probe provides a set of fields that could be accessed with the
ctx pointer. Users can display the set of available fields for each iterator via
-lv options as described below.

----
iter:task { printf("%s:%d\n", ctx->task->comm, ctx->task->pid); }

/*
 * Sample output:
 * systemd:1
 * kthreadd:2
 * rcu_gp:3
 * rcu_par_gp:4
 * kworker/0:0H:6
 * mm_percpu_wq:8
 */
----

----
iter:task_file {
  printf("%s:%d %d:%s\n", ctx->task->comm, ctx->task->pid, ctx->fd, path(ctx->file->f_path));
}

/*
 * Sample output:
 * systemd:1 1:/dev/null
 * systemd:1 3:/dev/kmsg
 * ...
 * su:1622 2:/dev/pts/1
 * ...
 * bpftrace:1892 2:/dev/pts/1
 * bpftrace:1892 6:anon_inode:bpf-prog
 */
----

----
iter:task_vma {
  printf("%s %d %lx-%lx\n", comm, pid, ctx->vma->vm_start, ctx->vma->vm_end);
}

/*
 * Sample output:
 * bpftrace 119480 55b92c380000-55b92c386000
 * ...
 * bpftrace 119480 7ffd55dde000-7ffd55de2000
 */
----

It's possible to pin an iterator by specifying the optional probe ':pin' part, that defines the pin file.
It can be specified as an absolute or relative path to /sys/fs/bpf.

.relative pin
----
iter:task:list { printf("%s:%d\n", ctx->task->comm, ctx->task->pid); }

/*
 * Sample output:
 * Program pinned to /sys/fs/bpf/list
 */
----

.absolute pin
----
iter:task_file:/sys/fs/bpf/files {
  printf("%s:%d %s\n", ctx->task->comm, ctx->task->pid, path(ctx->file->f_path));
}

/*
 * Sample output:
 * Program pinned to /sys/fs/bpf/files
 */
----

[#probes-fentry]
=== fentry and fexit

.variants
* `fentry[:module]:fn`
* `fexit[:module]:fn`

.short names
* `f` (`fentry`)
* `fr` (`fexit`)

.requires (`--info`)
* Kernel features:BTF
* Probe types:fentry

``fentry``/``fexit`` probes attach to kernel functions similar to <<probes-kprobe>>.
They make use of eBPF trampolines which allow kernel code to call into BPF programs with near zero overhead.
Originally, these were called `kfunc` and `kretfunc` but were later renamed to `fentry` and `fexit` to match
how these are referenced in the kernel and to prevent confusion with https://docs.kernel.org/bpf/kfuncs.html[BPF Kernel Functions].
The original names are still supported for backwards compatibility.

``fentry``/``fexit`` probes make use of BTF type information to derive the type of function arguments at compile time.
This removes the need for manual type casting and makes the code more resilient against small signature changes in the kernel.
The function arguments are available in the `args` struct which can be inspected by doing verbose listing (see <<Listing Probes>>).
These arguments are also available in the return probe (`fexit`), unlike `kretprobe`.

----
# bpftrace -lv 'fentry:tcp_reset'

fentry:tcp_reset
    struct sock * sk
    struct sk_buff * skb
----

----
fentry:x86_pmu_stop {
  printf("pmu %s stop\n", str(args.event->pmu->name));
}
----

The fget function takes one argument as file descriptor and you can access it via args.fd and the return value is accessible via retval:

----
fexit:fget {
  printf("fd %d name %s\n", args.fd, str(retval->f_path.dentry->d_name.name));
}

/*
 * Sample output:
 * fd 3 name ld.so.cache
 * fd 3 name libselinux.so.1
 */
----

[#probes-kprobe]
=== kprobe and kretprobe

.variants
* `kprobe[:module]:fn`
* `kprobe[:module]:fn+offset`
* `kretprobe[:module]:fn`

.short names
* `k`
* `kr`

``kprobe``s allow for dynamic instrumentation of kernel functions.
Each time the specified kernel function is executed the attached BPF programs are ran.

----
kprobe:tcp_reset {
  @tcp_resets = count()
}
----

Function arguments are available through the `argN` for register args. Arguments passed on stack are available using the stack pointer, e.g. `$stack_arg0 = *(int64*)reg("sp") + 16`.
Whether arguments passed on stack or in a register depends on the architecture and the number or arguments used, e.g. on x86_64 the first 6 non-floating point arguments are passed in registers and all following arguments are passed on the stack.
Note that floating point arguments are typically passed in special registers which don't count as `argN` arguments which can cause confusion.
Consider a function with the following signature:

----
void func(int a, double d, int x)
----

Due to `d` being a floating point, `x` is accessed through `arg1` where one might expect `arg2`.

bpftrace does not detect the function signature so it is not aware of the argument count or their type.
It is up to the user to perform <<Type conversion>> when needed, e.g.

----
#include <linux/path.h>
#include <linux/dcache.h>

kprobe:vfs_open
{
	printf("open path: %s\n", str(((struct path *)arg0)->dentry->d_name.name));
}
----

Here arg0 was cast as a (struct path *), since that is the first argument to vfs_open.
The struct support is the same as bcc and based on available kernel headers.
This means that many, but not all, structs will be available, and you may need to manually define structs.

If the kernel has BTF (BPF Type Format) data, all kernel structs are always available without defining them. For example:

----
kprobe:vfs_open {
  printf("open path: %s\n", str(((struct path *)arg0)->dentry->d_name.name));
}
----

You can optionally specify a kernel module, either to include BTF data from that module, or to specify that the traced function should come from that module.

----
kprobe:kvm:x86_emulate_insn
{
  $ctxt = (struct x86_emulate_ctxt *) arg0;
  printf("eip = 0x%lx\n", $ctxt->eip);
}
----

See <<BTF Support>> for more details.

`kprobe` s are not limited to function entry, they can be attached to any instruction in a function by specifying an offset from the start of the function.

`kretprobe` s trigger on the return from a kernel function.
Return probes do not have access to the function (input) arguments, only to the return value (through `retval`).
A common pattern to work around this is by storing the arguments in a map on function entry and retrieving in the return probe:

----
kprobe:d_lookup
{
	$name = (struct qstr *)arg1;
	@fname[tid] = $name->name;
}

kretprobe:d_lookup
/@fname[tid]/
{
	printf("%-8d %-6d %-16s M %s\n", elapsed / 1e6, pid, comm,
	    str(@fname[tid]));
}
----

[#probes-profile]
=== profile

.variants
* `profile:count`
* `profile:us:count`
* `profile:ms:count`
* `profile:s:count`
* `profile:hz:rate`

.short name
* `p`

Profile probes fire on each CPU on the specified interval.
These operate using perf_events (a Linux kernel facility, which is also used by the perf command).
If a unit of time is not specified in the second position, the number is interpreted as nanoseconds; e.g., `interval:1s`, `interval:1000000000`, and `interval:s:1` are all equivalent.

----
profile:hz:99 { @[tid] = count(); }
----

[#probes-rawtracepoint]
=== rawtracepoint

.variants
* `rawtracepoint[:module]:event`

.short name
* `rt`

Raw tracepoints are attached to the same tracepoints as normal tracepoint programs.
The reason why you might want to use raw tracepoints over normal tracepoints is due to the performance improvement - https://docs.ebpf.io/linux/program-type/BPF_PROG_TYPE_RAW_TRACEPOINT/[Read More].

`rawtracepoint` arguments can be accessed via the `argN` builtins AND via the `args` builtin.

----
rawtracepoint:vmlinux:kfree_skb {
  printf("%llx %llx\n", arg0, args.skb);
}
----
`arg0` and `args.skb` will print the same address.

`rawtracepoint` probes make use of BTF type information to derive the type of function arguments at compile time.
This removes the need for manual type casting and makes the code more resilient against small signature changes in the kernel.
The arguments accessible by a `rawtracepoint` are different from the arguments you can access from the `tracepoint` of the same name.
The function arguments are available in the `args` struct which can be inspected by doing verbose listing (see <<Listing Probes>>).

[#probes-software]
=== software

.variants
* `software:event:`
* `software:event:count`

.short name
* `s`

These are the pre-defined software events provided by the Linux kernel, as commonly traced via the perf utility.
They are similar to tracepoints, but there is only about a dozen of these, and they are documented in the perf_event_open(2) man page.
If the count is not provided, a default is used.

The event names are:

- `cpu-clock` or `cpu`
- `task-clock`
- `page-faults` or `faults`
- `context-switches` or `cs`
- `cpu-migrations`
- `minor-faults`
- `major-faults`
- `alignment-faults`
- `emulation-faults`
- `dummy`
- `bpf-output`

----
software:faults:100 { @[comm] = count(); }
----

This roughly counts who is causing page faults, by sampling the process name for every one in one hundred faults.

[#probes-tracepoint]
=== tracepoint

.variants
* `tracepoint:subsys:event`

.short name
* `t`

Tracepoints are hooks into events in the kernel.
Tracepoints are defined in the kernel source and compiled into the kernel binary which makes them a form of static tracing.
Unlike `kprobe` s, new tracepoints cannot be added without modifying the kernel.

The advantage of tracepoints is that they generally provide a more stable interface than `kprobe` s do, they do not depend on the existence of a kernel function.

----
tracepoint:syscalls:sys_enter_openat {
  printf("%s %s\n", comm, str(args.filename));
}
----

Tracepoint arguments are available in the `args` struct which can be inspected with verbose listing, see the <<Listing Probes>> section for more details.

----
# bpftrace -lv "tracepoint:*"

tracepoint:xhci-hcd:xhci_setup_device_slot
  u32 info
  u32 info2
  u32 tt_info
  u32 state
...
----

Alternatively members for each tracepoint can be listed from their /format file in /sys.

Apart from the filename member, we can also print flags, mode, and more.
After the "common" members listed first, the members are specific to the tracepoint.

.Additional information
* https://www.kernel.org/doc/html/latest/trace/tracepoints.html

[#probes-uprobe]
=== uprobe, uretprobe

.variants
* `uprobe:binary:func`
* `uprobe:binary:func+offset`
* `uprobe:binary:offset`
* `uretprobe:binary:func`

.short names
* `u`
* `ur`

`uprobe` s or user-space probes are the user-space equivalent of `kprobe` s.
The same limitations that apply <<probes-kprobe>> also apply to `uprobe` s and `uretprobe` s, namely: arguments are available via the `argN` and `sargN` builtins and can only be accessed with a uprobe (`sargN` is more common for older versions of golang).
retval is the return value for the instrumented function and can only be accessed with a uretprobe.

----
uprobe:/bin/bash:readline { printf("arg0: %d\n", arg0); }
----

What does arg0 of readline() in /bin/bash contain?
I don't know, so I'll need to look at the bash source code to find out what its arguments are.

When tracing libraries, it is sufficient to specify the library name instead of
a full path. The path will be then automatically resolved using `/etc/ld.so.cache`:

----
uprobe:libc:malloc { printf("Allocated %d bytes\n", arg0); }
----

If the traced binary has DWARF included, function arguments are available in the `args` struct which can be inspected with verbose listing, see the <<Listing Probes>> section for more details.

----
# bpftrace -lv 'uprobe:/bin/bash:rl_set_prompt'

uprobe:/bin/bash:rl_set_prompt
    const char* prompt
----

When tracing C{plus}{plus} programs, it's possible to turn on automatic symbol demangling by using the `:cpp` prefix:

----
# bpftrace:cpp:"bpftrace::BPFtrace::add_probe" { ... }
----

It is important to note that for `uretprobe` s to work the kernel runs a special helper on user-space function entry which overrides the return address on the stack.
This can cause issues with languages that have their own runtime like Golang:

.example.go
----
func myprint(s string) {
  fmt.Printf("Input: %s\n", s)
}

func main() {
  ss := []string{"a", "b", "c"}
  for _, s := range ss {
    go myprint(s)
  }
  time.Sleep(1*time.Second)
}
----

.bpftrace
----
# bpftrace -e 'uretprobe:./test:main.myprint { @=count(); }' -c ./test
runtime: unexpected return pc for main.myprint called from 0x7fffffffe000
stack: frame={sp:0xc00008cf60, fp:0xc00008cfd0} stack=[0xc00008c000,0xc00008d000)
fatal error: unknown caller pc
----

[#probes-usdt]
=== usdt

.variants
* `usdt:binary_path:probe_name`
* `usdt:binary_path:[probe_namespace]:probe_name`
* `usdt:library_path:probe_name`
* `usdt:library_path:[probe_namespace]:probe_name`

.short name
* `U`

Where probe_namespace is optional if probe_name is unique within the binary.

You can target the entire host (or an entire process's address space by using the `-p` arg) by using a single wildcard in place of the binary_path/library_path:

----
usdt:*:loop { printf("hi\n"); }
----

Please note that if you use wildcards for the probe_name or probe_namespace and end up targeting multiple USDTs for the same probe you might get errors if you also utilize the USDT argument builtin (e.g. arg0) as they could be of different types.

Arguments are available via the `argN` builtins:

----
usdt:/root/tick:loop { printf("%s: %d\n", str(arg0), arg1); }
----

bpftrace also supports USDT semaphores.
If both your environment and bpftrace support uprobe refcounts, then USDT semaphores are automatically activated for all processes upon probe attachment (and --usdt-file-activation becomes a noop).
You can check if your system supports uprobe refcounts by running:

----
# bpftrace --info 2>&1 | grep "uprobe refcount"
bcc bpf_attach_uprobe refcount: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes
----

If your system does not support uprobe refcounts, you may activate semaphores by passing in -p $PID or --usdt-file-activation.
--usdt-file-activation looks through /proc to find processes that have your probe's binary mapped with executable permissions into their address space and then tries to attach your probe.
Note that file activation occurs only once (during attach time).
In other words, if later during your tracing session a new process with your executable is spawned, your current tracing session will not activate the new process.
Also note that --usdt-file-activation matches based on file path.
This means that if bpftrace runs from the root host, things may not work as expected if there are processes execved from private mount namespaces or bind mounted directories.
One workaround is to run bpftrace inside the appropriate namespaces (i.e. the container).

[#probes-watchpoint]
=== watchpoint and asyncwatchpoint

.variants
* `watchpoint:absolute_address:length:mode`
* `watchpoint:function+argN:length:mode`

.short names
* `w`
* `aw`

This feature is experimental and may be subject to interface changes.
Memory watchpoints are also architecture dependent.

These are memory watchpoints provided by the kernel.
Whenever a memory address is written to (`w`), read
from (`r`), or executed (`x`), the kernel can generate an event.

In the first form, an absolute address is monitored.
If a pid (`-p`) or a command (`-c`) is provided, bpftrace takes the address as a userspace address and monitors the appropriate process.
If not, bpftrace takes the address as a kernel space address.

In the second form, the address present in `argN` when `function` is entered is
monitored.
A pid or command must be provided for this form.
If synchronous (`watchpoint`), a `SIGSTOP` is sent to the tracee upon function entry.
The tracee will be ``SIGCONT``ed after the watchpoint is attached.
This is to ensure events are not missed.
If you want to avoid the `SIGSTOP` + `SIGCONT` use `asyncwatchpoint`.

Note that on most architectures you may not monitor for execution while monitoring read or write.

----
# bpftrace -e 'watchpoint:0x10000000:8:rw { printf("hit!\n"); }' -c ./testprogs/watchpoint
----

Print the call stack every time the `jiffies` variable is updated:

----
watchpoint:0x$(awk '$3 == "jiffies" {print $1}' /proc/kallsyms):8:w {
  @[kstack] = count();
}
----

"hit" and exit when the memory pointed to by `arg1` of `increment` is written to:

[,C]
----
# cat wpfunc.c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

__attribute__((noinline))
void increment(__attribute__((unused)) int _, int *i)
{
  (*i)++;
}

int main()
{
  int *i = malloc(sizeof(int));
  while (1)
  {
    increment(0, i);
    (*i)++;
    usleep(1000);
  }
}
----

----
# bpftrace -e 'watchpoint:increment+arg1:4:w { printf("hit!\n"); exit() }' -c ./wpfunc
----

Note that threads are monitored, but only for threads created after watchpoint attachment.
The is a limitation from the kernel.
Additionally, because of how watchpoints are implemented in bpftrace the specified function must be called at least once in the main thread in order to observe future calls to this function in child threads.

== Standard library

The standard library of all builtins, functions, and map functions is link:https://github.com/bpftrace/bpftrace/blob/master/docs/stdlib.md[available here].

== Configuration

- <<Config Variables>>
- <<Environment Variables>>

=== Config Variables

Some behavior can only be controlled through config variables, which are listed here.
These can be set via the <<Config Block>> directly in a script (before any probes) or via their environment variable equivalent, which is upper case and includes the `BPFTRACE_` prefix e.g. ``stack_mode``'s environment variable would be `BPFTRACE_STACK_MODE`.

==== cache_user_symbols

Default: PER_PROGRAM if ASLR disabled or `-c` option given, PER_PID otherwise.

- PER_PROGRAM - each program has its own cache. If there are more processes with enabled ASLR for a single program, this might produce incorrect results.
- PER_PID - each process has its own cache. This is accurate for processes with ASLR enabled, and enables bpftrace to preload caches for processes running at probe attachment ti
me.
If there are many processes running, it will consume a lot of a memory.
- NONE - caching disabled. This saves the most memory, but at the cost of speed.

==== cpp_demangle

Default: true

C++ symbol demangling in userspace stack traces is enabled by default.

This feature can be turned off by setting the value of this variable to `false`.

==== lazy_symbolication

Default: false

For user space symbols, symbolicate lazily/on-demand (`true`) or symbolicate everything ahead of time (`false`).

==== license

Default: "GPL"

The license bpftrace will use to load BPF programs into the linux kernel.

==== log_size

Default: 1000000

Log size in bytes.

==== max_bpf_progs

Default: 1024

This is the maximum number of BPF programs (functions) that bpftrace can generate.
The main purpose of this limit is to prevent bpftrace from hanging since generating a lot of probes
takes a lot of resources (and it should not happen often).

==== max_cat_bytes

Default: 10240

Maximum bytes read by cat builtin.

==== max_map_keys

Default: 4096

This is the maximum number of keys that can be stored in a map.
Increasing the value will consume more memory and increase startup times.
There are some cases where you will want to, for example: sampling stack traces, recording timestamps for each page, etc.

==== max_probes

Default: 1024

This is the maximum number of probes that bpftrace can attach to.
Increasing the value will consume more memory, increase startup times, and can incur high performance overhead or even freeze/crash the
system.

==== max_strlen

Default: 1024

The maximum length (in bytes) for values created by `str()`, `buf()` and `path()`.

This limit is necessary because BPF requires the size of all dynamically-read strings (and similar) to be declared up front. This is the size for all strings (and similar) in bpftrace unless specified at the call site.
There is no artificial limit on what you can tune this to. But you may be wasting resources (memory and cpu) if you make this too high.

==== missing_probes

Default: `error`

Controls handling of probes which cannot be attached because they do not exist (in the kernel or in the traced binary) or there was an issue during attachment.

The possible options are:
- `error` - always fail on missing probes
- `warn` - print a warning but continue execution
- `ignore` - silently ignore missing probes

==== on_stack_limit

Default: 32

The maximum size (in bytes) of individual objects that will be stored on the BPF stack. If they are larger than this limit they will be stored in pre-allocated memory.

This exists because the BPF stack is limited to 512 bytes and large objects make it more likely that we'll run out of space. bpftrace can store objects that are larger than the `on_stack_limit` in pre-allocated memory to prevent this stack error. However, storing in pre-allocated memory may be less memory efficient. Lower this default number if you are still seeing a stack memory error or increase it if you're worried about memory consumption.

==== perf_rb_pages

Default: 64

Number of pages to allocate per CPU perf ring buffer.
The value must be a power of 2.
If you're getting a lot of dropped events bpftrace may not be processing events in the ring buffer fast enough.
It may be useful to bump the value higher so more events can be queued up.
The tradeoff is that bpftrace will use more memory.

==== show_debug_info

This is only available if the link:https://github.com/libbpf/blazesym[Blazesym] library is available at build time. If it is available this defaults to `true`, meaning that when printing ustack and kstack symbols bpftrace will also show (if debug info is available) symbol file and line ('bpftrace' stack mode) and a label if the function was inlined ('bpftrace' and 'perf' stack modes).
There might be a performance difference when symbolicating, which is the only reason to disable this.

==== stack_mode

Default: bpftrace

Output format for ustack and kstack builtins.
Available modes/formats:

- bpftrace
- perf
- raw: no symbolication

This can be overwritten at the call site.

==== str_trunc_trailer

Default: `..`

Trailer to add to strings that were truncated.
Set to empty string to disable truncation trailers.

==== print_maps_on_exit

Default: true

Controls whether maps are printed on exit. Set to `false` in order to change the default behavior and not automatically print maps at program exit.

==== unstable_macro

Default: warn

Feature flag for bpftrace macros.

The possible options are:
- `error` - fail if this feature is used
- `warn` - enable feature but print a warning
- `enable` - enable feature

==== unstable_map_decl

Default: warn

Feature flag for map declarations.

The possible options are:
- `error` - fail if this feature is used
- `warn` - enable feature but print a warning
- `enable` - enable feature

==== unstable_tseries

Default: warn

Feature flag for `tseries`.

The possible options are:
- `error` - fail if this feature is used
- `warn` - enable feature but print a warning
- `enable` - enable feature

=== Environment Variables

These are not available as part of the standard set of <<Config Variables>> and can only be set as environment variables.

==== BPFTRACE_BTF

Default: None

The path to a BTF file. By default, bpftrace searches several locations to find a BTF file.
See src/btf.cpp for the details.

==== BPFTRACE_DEBUG_OUTPUT

Default: 0

Outputs bpftrace's runtime debug messages to the trace_pipe. This feature can be turned on by setting
the value of this environment variable to `1`.

==== BPFTRACE_KERNEL_BUILD

Default: `/lib/modules/$(uname -r)`

Only used with `BPFTRACE_KERNEL_SOURCE` if it is out-of-tree Linux kernel build.

==== BPFTRACE_KERNEL_SOURCE

Default: `/lib/modules/$(uname -r)`

bpftrace requires kernel headers for certain features, which are searched for in this directory.

==== BPFTRACE_VMLINUX

Default: None

This specifies the vmlinux path used for kernel symbol resolution when attaching kprobe to offset.
If this value is not given, bpftrace searches vmlinux from pre defined locations.
See src/attached_probe.cpp:find_vmlinux() for details.

==== BPFTRACE_COLOR

Default: auto

Colorize the bpftrace log output message. Valid values are auto, always and never.

== Advanced Topics

=== Address Spaces

Kernel and user pointers live in different address spaces which, depending on the CPU architecture, might overlap.
Trying to read a pointer that is in the wrong address space results in a runtime error.
This error is hidden by default but can be enabled with the `-k` flag:

----
stdin:1:9-12: WARNING: Failed to probe_read_user: Bad address (-14)
BEGIN { @=*uptr(kaddr("do_poweroff")) }
        ~~~
----

bpftrace tries to automatically set the correct address space for a pointer based on the probe type, but might fail in cases where it is unclear.
The address space can be changed with the <<functions-kptr, kptrs>> and <<functios-uptr, uptr>> functions.

=== BPF License

By default bpftrace uses "GPL", which is actually "GPL version 2", as the license it uses to load BPF programs into the kernel.
Some other examples of compatible licenses are: "GPL v2" and "Dual MPL/GPL".
You can specify a different license using the "license" config variable.
link:https://docs.kernel.org/bpf/bpf_licensing.html#using-bpf-programs-in-the-linux-kernel[#Read more about BPF programs and licensing].

=== BTF Support

If the kernel version has BTF support, kernel types are automatically available and there is no need to include additional headers to use them.
It is not recommended to mix definitions from multiple sources (ie. BTF and header files).
If your program mixes definitions, bpftrace will do its best but can easily get confused due to redefinition conflicts.
Prefer to exclusively use BTF as it can never get out of sync on a running system. BTF is also less susceptible to parsing failures (C is constantly evolving).
Almost all current linux deployments will support BTF.

To allow users to detect this situation in scripts, the preprocessor macro `BPFTRACE_HAVE_BTF` is defined if BTF is detected.
See `tools/` for examples of its usage.

Requirements for using BTF for vmlinux:

* Linux 4.18+ with CONFIG_DEBUG_INFO_BTF=y
** Building requires dwarves with pahole v1.13+
* bpftrace v0.9.3+ with BTF support (built with libbpf v0.0.4+)

Additional requirements for using BTF for kernel modules:

* Linux 5.11+ with CONFIG_DEBUG_INFO_BTF_MODULES=y
** Building requires dwarves with pahole v1.19+

See kernel documentation for more information on BTF.

=== Clang Environment Variables

bpftrace parses header files using libclang, the C interface to Clang.
Thus environment variables affecting the clang toolchain can be used.
For example, if header files are included from a non-default directory, the `CPATH` or `C_INCLUDE_PATH` environment variables can be set to allow clang to locate the files.
See clang documentation for more information on these environment variables and their usage.

=== Complex Tools

bpftrace can be used to create some powerful one-liners and some simple tools.
For complex tools, which may involve command line options, positional parameters, argument processing, and customized output, consider switching to bcc.
bcc provides Python (and other) front-ends, enabling usage of all the other Python libraries (including argparse), as well as a direct control of the kernel BPF program.
The down side is that bcc is much more verbose and laborious to program.
Together, bpftrace and bcc are complimentary.

An expected development path would be exploration with bpftrace one-liners, then and ad hoc scripting with bpftrace, then finally, when needed, advanced tooling with bcc.

As an example of bpftrace vs bcc differences, the bpftrace xfsdist.bt tool also exists in bcc as xfsdist.py. Both measure the same functions and produce the same summary of information.
However, the bcc version supports various arguments:

----
# ./xfsdist.py -h
usage: xfsdist.py [-h] [-T] [-m] [-p PID] [interval] [count]

Summarize XFS operation latency

positional arguments:
  interval            output interval, in seconds
  count               number of outputs

optional arguments:
  -h, --help          show this help message and exit
  -T, --notimestamp   don't include timestamp on interval output
  -m, --milliseconds  output in milliseconds
  -p PID, --pid PID   trace this PID only

examples:
    ./xfsdist            # show operation latency as a histogram
    ./xfsdist -p 181     # trace PID 181 only
    ./xfsdist 1 10       # print 1 second summaries, 10 times
    ./xfsdist -m 5       # 5s summaries, milliseconds
----

The bcc version is 131 lines of code. The bpftrace version is 22.

=== Errors

. Looks like the BPF stack limit of 512 bytes is exceeded BPF programs that operate on many data items may hit this limit.
There are a number of things you can try to stay within the limit:

.. Find ways to reduce the size of the data used in the program. Eg, avoid strings if they are unnecessary: use pid instead of comm. Use fewer map keys.
.. Split your program over multiple probes.
.. Check the status of the BPF stack limit in Linux (it may be increased in the future, maybe as a tuneable).
.. (advanced): Run -d and examine the LLVM IR, and look for ways to optimize src/ast/codegen_llvm.cpp.
. Kernel headers not found
bpftrace requires kernel headers for certain features, which are searched for by default in: `/lib/modules/$(uname -r)`.
The default search directory can be overridden using the environment variable BPFTRACE_KERNEL_SOURCE and also BPFTRACE_KERNEL_BUILD if it is out-of-tree Linux kernel build.

=== Invocation Mode

There are three invocation modes for bpftrace built-in functions.

[cols="~,~,~"]
|===

| Mode
| Description
| Example functions

| Synchronous
| The value/effect of the built-in function is determined/handled right away by the bpf program in the kernel space.
| `reg(), str(), ntop()`

| Asynchronous
| The value/effect of the built-in function is determined/handled later by the bpftrace process in the user space.
| `printf(), clear(), exit()`

| Compile-time
| The value of the built-in function is determined before bpf programs are running.
| `kaddr(), cgroupid(), offsetof()`

|===

While BPF in the kernel can do a lot there are still things that can only be done from user space, like the outputting (printing) of data.
The way bpftrace handles this is by sending events from the BPF program which user-space will pick up some time in the future (usually in milliseconds).
Operations that happen in the kernel are 'synchronous' ('sync') and those that are handled in user space are 'asynchronous' ('async')

The asynchronous behaviour can lead to some unexpected behavior as updates can happen before user space had time to process the event. The following situations may occur:

* event loss: when using printf(), the amount of data printed may be less than the actual number of events generated by the kernel during BPF program's execution.
* delayed exit: when using the exit() to terminate the program, bpftrace needs to handle the exit signal asynchronously causing the BPF program may continue to run for some additional time.

One example is updating a map value in a tight loop:

----
BEGIN {
    @=0;
    unroll(10) {
      print(@);
      @++;
    }
    exit()
}
----

Maps are printed by reference not by value and as the value gets updated right after the print user-space will likely only see the final value once it processes the event:

----
@: 10
@: 10
@: 10
@: 10
@: 10
@: 10
@: 10
@: 10
@: 10
@: 10
----

Therefore, when you need precise event statistics, it is recommended to use synchronous functions (e.g. count() and hist()) to ensure more reliable and accurate results.

=== Map Printing

By default when a bpftrace program exits it will print all maps to stdout.
If you don't want this, you can either override the `print_maps_on_exit` configuration option or you can specify an `END` probe and `clear` the maps you don't want printed.

For example, these two scripts are equivalent and will print nothing on exit:
```
config = {
  print_maps_on_exit=0
}

BEGIN {
  @a = 1;
  @b[1] = 1;
}
```

```
BEGIN {
  @a = 1;
  @b[1] = 1;
}

END {
  clear(@a);
  clear(@b);
}
```

=== Options Expanded

==== Debug Output

The `-d STAGE` option produces debug output. It prints the output of the
bpftrace execution stage given by the _STAGE_ argument. The option can be used
multiple times (with different stage names) and the special value `all` prints
the output of all the supported stages. The option also takes multiple stages
in one invocation as comma separated values.

Note: This is primarily used for bpftrace developers.

The supported options are:

[cols="~,~"]
|===

| `ast`
| Prints the Abstract Syntax Tree (AST) after every pass.

| `codegen`
| Prints the unoptimized LLVM IR as produced by `CodegenLLVM`.

| `codegen-opt`
| Prints the optimized LLVM IR, i.e. the code which will be compiled into BPF
bytecode.

| `dis`
| Disassembles and prints out the generated bytecode that `libbpf` will see.
Only available in debug builds.

| `libbpf`
| Captures and prints libbpf log for all libbpf operations that bpftrace uses.

| `verifier`
| Captures and prints the BPF verifier log.

| `all`
| Prints the output of all of the above stages.

|===

==== Listing Probes

Probe listing is the method to discover which probes are supported by the current system.
Listing supports the same syntax as normal attachment does and alternatively can be
combined with `-e` or filename args to see all the probes that a program would attach to.

----
# bpftrace -l 'kprobe:*'
# bpftrace -l 't:syscalls:*openat*
# bpftrace -l 'kprobe:tcp*,trace
# bpftrace -l 'k:*socket*,tracepoint:syscalls:*tcp*'
# bpftrace -l -e 'tracepoint:xdp:mem_* { exit(); }'
# bpftrace -l my_script.bt
# bpftrace -lv 'enum cpu_usage_stat'
----

The verbose flag (`-v`) can be specified to inspect arguments (`args`) for providers that support it:

----
# bpftrace -l 'fexit:tcp_reset,tracepoint:syscalls:sys_enter_openat' -v
fexit:tcp_reset
    struct sock * sk
    struct sk_buff * skb
tracepoint:syscalls:sys_enter_openat
    int __syscall_nr
    int dfd
    const char * filename
    int flags
    umode_t mode

# bpftrace -l 'uprobe:/bin/bash:rl_set_prompt' -v    # works only if /bin/bash has DWARF
uprobe:/bin/bash:rl_set_prompt
    const char *prompt

# bpftrace -lv 'struct css_task_iter'
struct css_task_iter {
        struct cgroup_subsys *ss;
        unsigned int flags;
        struct list_head *cset_pos;
        struct list_head *cset_head;
        struct list_head *tcset_pos;
        struct list_head *tcset_head;
        struct list_head *task_pos;
        struct list_head *cur_tasks_head;
        struct css_set *cur_cset;
        struct css_set *cur_dcset;
        struct task_struct *cur_task;
        struct list_head iters_node;
};
----

==== Preprocessor Options

The `-I` option can be used to add directories to the list of directories that bpftrace uses to look for headers.
Can be defined multiple times.

----
# cat program.bt
#include <foo.h>

BEGIN { @ = FOO }

# bpftrace program.bt

definitions.h:1:10: fatal error: 'foo.h' file not found

# /tmp/include
foo.h

# bpftrace -I /tmp/include program.bt

Attached 1 probe
----

The `--include` option can be used to include headers by default.
Can be defined multiple times.
Headers are included in the order they are defined, and they are included before any other include in the program being executed.

----
# bpftrace --include linux/path.h --include linux/dcache.h \
    -e 'kprobe:vfs_open { printf("open path: %s\n", str(((struct path *)arg0)->dentry->d_name.name)); }'

Attached 1 probe
open path: .com.google.Chrome.ASsbu2
open path: .com.google.Chrome.gimc10
open path: .com.google.Chrome.R1234s
----

==== Verbose Output

The `-v` option prints more information about the program as it is run:

----
# bpftrace -v -e 'tracepoint:syscalls:sys_enter_nanosleep { printf("%s is sleeping.\n", comm); }'
AST node count: 7
Attached 1 probe

load tracepoint:syscalls:sys_enter_nanosleep, with BTF, with func_infos: Success

Program ID: 111
Attaching tracepoint:syscalls:sys_enter_nanosleep
iscsid is sleeping.
iscsid is sleeping.
[...]
----

=== Systemd support

If bpftrace has been built with `-DENABLE_SYSTEMD=1`, one can run bpftrace in
the background using systemd::
----
# systemd-run --unit=bpftrace --service-type=notify bpftrace -e 'kprobe:do_nanosleep { printf("%d sleeping\n", pid); }'
----

In the above example, systemd-run will not finish until bpftrace has attached
its probes, so you can be sure that all following commands will be traced. To
stop tracing, run `systemctl stop bpftrace`.

To debug early boot issues, bpftrace can be invoked via a systemd service
ordered before the service that needs to be traced. A basic unit file to run
bpftrace before another service looks as follows::
----
[Unit]
Before=service-i-want-to-trace.service

[Service]
Type=notify
ExecStart=bpftrace -e 'kprobe:do_nanosleep { printf("%d sleeping\n", pid); }'
----

Similarly to the systemd-run example, the service to be traced will not start
until bpftrace started by the systemd unit has attached its probes.

=== PER_CPU types

For bpftrace PER_CPU types (search this document for "PER_CPU"), you may coerce
(and thus force a more expensive synchronous read) the type to an integer using
a cast or by doing a comparison. This is useful for when you need an integer
during comparisons, `printf()`, or other.

For example:

----
BEGIN {
  @c = count();
  @s = sum(3);
  @s = sum(9);

  if (@s == 12) {                             // Coerces @s
    printf("%d %d\n", (int64)@c, (int64)@s);  // Coerces @c and @s and prints "1 12"
  }
}
----

=== Unstable Features

Some features added to bpftrace are not yet stable.
They are enabled by default but come with a warning if used.
If you explicitly add the config variable to your script the warning will not be shown e.g.
```
config = {
    unstable_map_decl=enable;
}
```

To opt-out of these unstable features (and ensure they are not used) add the config variable and set it to `error` e.g.
```
config = {
    unstable_map_decl=error;
}
```

Note: all unstable features are subject to change and/or removal.

== Terminology

[cols="~,~"]
|===

| BPF
| Berkeley Packet Filter: a kernel technology originally developed for optimizing the processing of packet filters (eg, tcpdump expressions).

| BPF map
| A BPF memory object, which is used by bpftrace to create many higher-level objects.

| BTF
| BPF Type Format: the metadata format which encodes the debug info related to BPF program/map.

| dynamic tracing
| Also known as dynamic instrumentation, this is a technology that can instrument any software event, such as function calls and returns, by live modification of instruction text. Target software usually does not need special capabilities to support dynamic tracing, other than a symbol table that bpftrace can read. Since this instruments all software text, it is not considered a stable API, and the target functions may not be documented outside of their source code.

| eBPF
| Enhanced BPF: a kernel technology that extends BPF so that it can execute more generic programs on any events, such as the bpftrace programs listed below. It makes use of the BPF sandboxed virtual machine environment. Also note that eBPF is often just referred to as BPF.

| kprobes
| A Linux kernel technology for providing dynamic tracing of kernel functions.

| probe
| An instrumentation point in software or hardware, that generates events that can execute bpftrace programs.

| static tracing
| Hard-coded instrumentation points in code. Since these are fixed, they may be provided as part of a stable API, and documented.

| tracepoints
| A Linux kernel technology for providing static tracing.

| uprobes
| A Linux kernel technology for providing dynamic tracing of user-level functions.

| USDT
| User Statically-Defined Tracing: static tracing points for user-level software. Some applications support USDT.

|===

== Supported architectures

x86_64, arm64, s390x, arm32, loongarch64, mips64, ppc64, riscv64

== Program Files

Programs saved as files are often called scripts and can be executed by specifying their file name.
It is convention to use the `.bt` file extension but it is not required.

For example, listing the sleepers.bt file using `cat`:

----
# cat sleepers.bt

tracepoint:syscalls:sys_enter_nanosleep {
  printf("%s is sleeping.\n", comm);
}
----

And then calling it:

----
# bpftrace sleepers.bt

Attached 1 probe
iscsid is sleeping.
iscsid is sleeping.
----

It can also be made executable to run stand-alone.
Start by adding an interpreter line at the top (`#!`) with either the path to your installed bpftrace (/usr/local/bin is the default) or the path to `env` (usually just `/usr/bin/env`) followed by `bpftrace` (so it will find bpftrace in your `$PATH`):

----
#!/usr/local/bin/bpftrace

tracepoint:syscalls:sys_enter_nanosleep {
  printf("%s is sleeping.\n", comm);
}
----

Then make it executable:

----
# chmod 755 sleepers.bt
# ./sleepers.bt

Attached 1 probe
iscsid is sleeping.
iscsid is sleeping.
----
