name: Changelog reminder

# Configure to skip this workflow if CHANGELOG.md was modified
on:
  pull_request:
    paths-ignore:
    - "CHANGELOG.md"

jobs:
  comment-on-pr:
    if: "github.repository == 'iovisor/bpftrace'"
    runs-on: ubuntu-latest
    steps:
    - uses: github-actions-up-and-running/pr-comment@v1.0.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        message: MY MESSAGE
