name: Changelog reminder

# Configure to skip this workflow if CHANGELOG.md was modified
on:
  pull_request:
    paths-ignore:
    - "CHANGELOG.md"

jobs:
  comment-on-pr:
    if: "github.repository == 'iovisor/bpftrace'"
    runs-on: ubuntu-latest
    steps:
    - uses: thollander/actions-comment-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: "MY MESSAGE"
