name: Distros

on: [push]

# Cancel previous run if a new one is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        dockerfile:
        - docker/Dockerfile.debian
        - docker/Dockerfile.fedora
        - docker/Dockerfile.ubuntu

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build -f ${{ matrix.dockerfile }} .
