name: Mergeable

on: [pull_request]

jobs:
  # This checks if the PR is towards a user branch. All other branches are
  # allowed, but the user should push manually in this case.
  user:
    name: User branch check
    runs-on: ubuntu-latest
    steps:
    - if: startsWith(github.base_ref, 'user/')
      run: |
        echo "### user/ branch found; do not merge :no_entry_sign:" >> $GITHUB_STEP_SUMMARY
        exit 1
